# Generated by Django 3.0.5 on 2020-05-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingDetails',
            new_name='ShippingDetail',
        ),
    ]
