# Generated by Django 3.0.5 on 2020-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20200514_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isCompleted',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isAvailable',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
