# Generated by Django 3.0.5 on 2020-05-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_auto_20200514_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('phone', 'Phones'), ('headphone', 'Headphones'), ('headset', 'Headsets'), ('laptop', 'Laptops')], max_length=100)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopApp.Product')),
            ],
        ),
    ]
