# Generated by Django 3.0.5 on 2020-05-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_auto_20200515_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
