# Generated by Django 3.0.5 on 2020-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_auto_20200515_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Some dummy desc for development stage'),
        ),
    ]
