# Generated by Django 3.0.5 on 2020-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='item_main_pics'),
        ),
    ]
